# Generated by Django 2.2.12 on 2020-06-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productinbasket_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
