# Generated by Django 2.2.12 on 2020-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price_per_item_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
