# Generated by Django 2.2.12 on 2020-08-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200809_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='discount',
            new_name='discount_of_product',
        ),
    ]
