# Generated by Django 2.2.12 on 2020-08-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_price_with_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_with_discount',
        ),
    ]
