# Generated by Django 2.2.12 on 2020-10-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='Транслит'),
        ),
    ]
